### ISSUE TITLE
error occuring

### ISSUE THREAD

**Issue by Punith1997** [Gunjan933/tutorial-pdf-downloader#1]
returning an error  '"return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2212' in position 4306: character maps to <undefined>"

**Comment by gunjannandy** [comment]
@Punith1997 Can you share more information about the issue you are facing?
Share `download_links.py`, and your system information (OS, Python version, environment, etc)

**Comment by ts23944** [comment]
> @Punith1997 Can you share more information about the issue you are facing? Share `download_links.py`, and your system information (OS, Python version, environment, etc)
PS C:\Users\D4yDr34m\Downloads\tutorial-pdf-downloader-master\tutorial-pdf-downloader-master> python main.py -t
Traceback (most recent call last):
  File "C:\Users\D4yDr34m\Downloads\tutorial-pdf-downloader-master\tutorial-pdf-downloader-master\main.py", line 7, in <module>
    import requests, time, os, sys, weasyprint, argparse, fnmatch, shutil
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\weasyprint\__init__.py", line 325, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\weasyprint\css\__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\weasyprint\css\computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\weasyprint\text\ffi.py", line 404, in <module>
    gobject = _dlopen(
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\weasyprint\text\ffi.py", line 391, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\D4yDr34m\AppData\Roaming\Python\Python310\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

I got above error show up when I try to download pdf with :python main.py -t
Please help me to solve this problem.. Thank you
